const NS = '@user/';

export const SET_BELL_SPEAKER = `${NS}SET_BELL_SPEAKER`;
export const SET_CALL_SPEAKER = `${NS}SET_CALL_SPEAKER`;
export const SET_MIC_DEVICE = `${NS}SET_MIC_DEVICE`;

export const FETCH_DEVICES_LIST = `${NS}FETCH_DEVICES_LIST`;

export const SAVE_SPEAKERS_LIST = `${NS}SAVE_SPEAKERS_LIST`;
export const SAVE_MICS_LIST = `${NS}SAVE_MICS_LIST`;

export const CHECK_CURRENT_SPEAKER = `${NS}CHECK_CURRENT_SPEAKER`;

export const SET_IS_PLAYING_SPEAKER = `${NS}SET_IS_PLAYING_SPEAKER`;
export const SAVE_IS_PLAYING_SPEAKER = `${NS}SAVE_IS_PLAYING_SPEAKER`;
